// AUTH CONSTANTS
export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_LOGOUT_USER = "SET_LOGOUT_USER";

// DRIVER MANAGEMENT
export const SET_DRIVER_LOADING = "SET_DRIVER_LOADING";
export const GET_ALL_DRIVERS = "GET_ALL_DRIVERS";
export const ADD_DRIVER_LOADING = "ADD_DRIVER_LOADING";
export const ADD_DRIVER = "ADD_DRIVER";

// VEHICLE MANAGEMENT
export const GET_ALL_VEHICLE_LOADING = "GET_ALL_VEHICLE_LOADING";
export const GET_ALL_VEHICLES = "GET_ALL_VEHICLES";
export const ADD_VEHICLE_LOADING = "ADD_VEHICLE_LOADING";
export const ADD_VEHICLE = "ADD_VEHICLE";
export const GET_ALL_VEHICLE_CATEGORY = "GET_ALL_VEHICLE_CATEGORY";
export const GET_VEHICLE_CATEGORY_LOADING = "GET_VEHICLE_CATEGORY_LOADING";
export const GET_ALL_VEHICLE_FUELTYPE = "GET_ALL_VEHICLE_FUELTYPE";
export const GET_VEHICLE_FUELTYPE_LOADING = "GET_VEHICLE_FUELTYPE_LOADING";
export const GET_ALL_VEHICLE_TYPE = "GET_ALL_VEHICLE_TYPE";
export const GET_VEHICLE_TYPE_LOADING = "GET_VEHICLE_TYPE_LOADING";

// TOKEN MANAGEMENT
export const ADD_TOKEN_LOADING = "ADD_TOKEN_LOADING";
export const ADD_TOKEN = "ADD_TOKEN";
export const GET_PENDING_TOKEN_LOADING = "GET_PENDING_TOKEN_LOADING";
export const GET_PENDING_TOKEN = "GET_PENDING_TOKEN";
export const GET_APPROVED_TOKEN_LOADING = "GET_APPROVED_TOKEN_LOADING";
export const GET_APPROVED_TOKEN = "GET_APPROVED_TOKEN";
export const GET_REJECTED_TOKEN_LOADING = "GET_REJECTED_TOKEN_LOADING";
export const GET_REJECTED_TOKEN = "GET_REJECTED_TOKEN";
export const TOKEN_APPROVE_LOADING = "TOKEN_APPROVE_LOADING";
export const TOKEN_APPROVE_MESSAGE = "TOKEN_APPROVE_MESSAGE";

// TRIP MANAGEMNT
export const SET_LON_LAT_FROM = "SET_LON_LAT_FROM";
export const SET_LON_LAT_TO = "SET_LON_LAT_TO";
export const SET_TRIP_DISTANCE = "SET_TRIP_DISTANCE";
export const GENERATE_TOKEN_LOADING = "GENERATE_TOKEN_LOADING";
export const GENERATE_TOKEN = "GENERATE_TOKEN";
export const CREATE_TRIP = "CREATE_TRIP";
export const CREATE_TRIP_LOADING = "CREATE_TRIP_LOADING";

// NOTIFICATION HANDLING
export const SET_NOTIFICATION = "SET_NOTIFICATION";

/******************************** */
/*********ERROR HANDLING********* */
/******************************** */
// AUTH ERROR
export const ERRORS_AUTH = "ERRORS_AUTH";

// DRIVER ERROR
export const ERRORS_GET_ALL_DRIVERS = "ERRORS_GET_ALL_DRIVERS";
export const ERRORS_ADD_DRIVER = "ERRORS_ADD_DRIVER";

// VEHICLE ERROR
export const ERRORS_GET_ALL_VEHICLES = "ERRORS_GET_ALL_VEHICLES";
export const ERRORS_ADD_VEHICLE = "ERRORS_ADD_VEHICLE";
export const ERRORS_GET_VEHICLE_CATEGORY = "ERRORS_GET_VEHICLE_CATEGORY";
export const ERRORS_GET_VEHICLE_FUELTYPE = "ERRORS_GET_VEHICLE_FUELTYPE";
export const ERRORS_GET_VEHICLE_TYPE = "ERRORS_GET_VEHICLE_TYPE";

// TOKEN ERROR
export const ERRORS_ADD_TOKEN = "ERRORS_ADD_TOKEN";
export const ERRORS_GET_PENDING_TOKEN = "ERRORS_GET_PENDING_TOKEN";
export const ERRORS_GET_APPROVED_TOKEN = "ERRORS_GET_APPROVED_TOKEN";
export const ERRORS_GET_REJECTED_TOKEN = "ERRORS_GET_REJECTED_TOKEN";
export const ERRORS_TOKEN_APPROVE = "ERRORS_TOKEN_APPROVE";

// TRIP ERRORS
export const ERRORS_GENERATE_TOKEN = "ERRORS_GENERATE_TOKEN"; 
export const ERRORS_CREATE_TRIP = "ERRORS_CREATE_TRIP"; 
