// AUTH CONSTANTS
export const GET_AUTH_ERRORS = "GET_ERRORS";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOGOUT_USER = "SET_LOGOUT_USER";

export const SET_DRIVER_LOADING = "SET_DRIVER_LOADING";
export const CREATE_DRIVER = "CREATE_DRIVER";
export const GET_ALL_DRIVERS = "GET_ALL_DRIVERS";
